baseUrl: https://yourdomain.com



spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:db}:3306/webapp_db
    username: root
    password: db-57xsl
    #password:  ${MYSQL_PASSWORD:db-57xsl}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/mysql/master.xml
